language: julia
os:
  - linux
  - osx
julia:
  - "1.0"
  - nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SwJ1644"); Pkg.test("SwJ1644"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("SwJ1644")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("Example2018")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
